### ISSUE TITLE
Properties are not resolved

### ISSUE THREAD

**Issue by kierendavies** [ckipp01/mill-giter8#11]
My `default.properties` contains these lines:
```
name=My New Service
module=$name;format="lower,word"$
package=com.zivver.$module$
```
which results in this output:
```
$ mill g8.validate
[2/6] g8.generate.overridden.io.kipp.mill.giter8.G8Module.generate
Ignoring unrecognized parameter: module=$name;format
Template applied in [...]
```
and sets the `package` property to literally `com.zivver.$module$` instead of `com.zivver.mynewservice`.

`G8Module.generate` calls [`G8.transformProps`](https://github.com/foundweekends/giter8/blob/b883ae197db8fdb107f27c9b451be79b10dc3fc9/library/src/main/scala/g8.scala#L375), but all that does is apply Maven version lookups. When it then passes the arguments to `G8.fromDirectory`, they are treated as literal and they are not resolved.  Giter8 itself usually does [a more complicated thing](https://github.com/foundweekends/giter8/blob/b883ae197db8fdb107f27c9b451be79b10dc3fc9/library/src/main/scala/g8.scala#L338) which seems to [always boil down to `applyTemplate`](https://github.com/foundweekends/giter8/blob/b883ae197db8fdb107f27c9b451be79b10dc3fc9/library/src/main/scala/g8.scala#L169).

`G8.fromDirectory` skips the interactive prompt if at least one property is passed as an argument. I suggest passing just the first property, since it generally ought to be a literal (or is required to be? I'm not sure).

**Comment by ckipp01** [comment]
Hey @kierendavies, thanks a lot for the report!

> G8Module.generate calls [G8.transformProps](https://github.com/foundweekends/giter8/blob/b883ae197db8fdb107f27c9b451be79b10dc3fc9/library/src/main/scala/g8.scala#L375), but all that does is apply Maven version lookups. When it then passes the arguments to G8.fromDirectory, they are treated as literal and they are not resolved. Giter8 itself usually does [a more complicated thing](https://github.com/foundweekends/giter8/blob/b883ae197db8fdb107f27c9b451be79b10dc3fc9/library/src/main/scala/g8.scala#L338) which seems to [always boil down to applyTemplate](https://github.com/foundweekends/giter8/blob/b883ae197db8fdb107f27c9b451be79b10dc3fc9/library/src/main/scala/g8.scala#L169).

Thanks a lot for digging in and linking all this. 🤔 I'll have to think a bit more about the best way to approach/fix this.
